include: package:dart_rules/analysis_options.yaml

linter:
  rules:
    avoid_function_literals_in_foreach_calls: false
    avoid_positional_boolean_parameters: false
    prefer_interpolation_to_compose_strings: false